#!/usr/bin/env python3
"""Regenerate .installer/shipped-hashes.txt from git history.

The installers' --uninstall / -Uninstall needs to recognize files that an
older LITE version installed, not only the ones the current checkout ships.
Hashing whole directories ties that check to one installer's dir-hash
algorithm, so I record per-file hashes instead: one
"<installed-relpath>\\t<sha256>" line for every version of every file any
main (or a release tag) ever shipped, under the path the installers copy it to.

I walk main's history, not HEAD's: a feature branch's intermediate commits
never reached users, and a squash merge drops them, so hashing them would make
the file differ between the PR and main. The working tree covers what the
branch is about to ship, so the result is the same set on the PR and on main
after the merge. CI regenerates the file on a full-history checkout and fails
on any diff, so a stale manifest can't reach main.

Usage (from anywhere inside the repo):
    python3 tools/gen-shipped-hashes.py
"""

from __future__ import annotations

import fnmatch
import hashlib
import re
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
OUTPUT = REPO_ROOT / ".installer" / "shipped-hashes.txt"
HEADER = "# generated by tools/gen-shipped-hashes.py — do not edit"

# 1.0.0 shipped from the repo root; 1.0.1 moved everything under plugin/.
PATHSPECS = (
    "plugin/skills",
    "plugin/hooks/examples",
    "plugin/templates",
    "skills",
    "hooks/examples",
    "templates",
)
TEMPLATE_FILES = ("CLAUDE.md.clayworks-template", "settings.example.json")


def git(*args: str) -> bytes:
    return subprocess.run(
        ["git", "-C", str(REPO_ROOT), *args],
        stdout=subprocess.PIPE,
        check=True,
    ).stdout


def installed_relpath(repo_path: str) -> str | None:
    """Map a repo path to where the installers put it, or None if unshipped."""
    path = repo_path[len("plugin/"):] if repo_path.startswith("plugin/") else repo_path
    parts = path.split("/")
    if parts[0] == "skills" and len(parts) >= 3 and parts[1].startswith("clayworks-lite-"):
        return path
    if parts[:2] == ["hooks", "examples"] and len(parts) >= 3:
        return path
    if parts[0] == "templates" and len(parts) == 2 and parts[1] in TEMPLATE_FILES:
        return parts[1]
    return None


def parse_gitattributes(text: str) -> list[tuple[str, dict[str, str]]]:
    """Parse the simple "<pattern> <attr>..." lines this repo uses."""
    rules = []
    for line in text.splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        pattern, *attrs = line.split()
        parsed: dict[str, str] = {}
        for attr in attrs:
            if attr == "binary":
                parsed["text"] = "unset"
            elif attr.startswith("-"):
                parsed[attr[1:]] = "unset"
            elif "=" in attr:
                key, value = attr.split("=", 1)
                parsed[key] = value
            else:
                parsed[attr] = "set"
        rules.append((pattern, parsed))
    return rules


def file_attrs(rules: list[tuple[str, dict[str, str]]], repo_path: str) -> dict[str, str]:
    """Resolve a path's attributes; a later matching line wins, as in git."""
    name = repo_path.rsplit("/", 1)[-1]
    attrs: dict[str, str] = {}
    for pattern, parsed in rules:
        target = repo_path if "/" in pattern else name
        if fnmatch.fnmatchcase(target, pattern.lstrip("/")):
            attrs.update(parsed)
    return attrs


def checkout_can_be_crlf(attrs: dict[str, str]) -> bool:
    """True unless .gitattributes pins the file to LF or marks it binary.

    A Windows checkout with core.autocrlf materializes every other text file
    with CRLF, so the installers copy CRLF bytes for those.
    """
    return attrs.get("text") != "unset" and attrs.get("eol") != "lf"


def variants(data: bytes, crlf_ok: bool) -> set[bytes]:
    out = {data}
    if crlf_ok:
        out.add(re.sub(rb"(?<!\r)\n", b"\r\n", data))
    return out


class BlobReader:
    """Read blobs through one long-lived `git cat-file --batch`."""

    def __init__(self) -> None:
        self.proc = subprocess.Popen(
            ["git", "-C", str(REPO_ROOT), "cat-file", "--batch"],
            stdin=subprocess.PIPE,
            stdout=subprocess.PIPE,
        )
        self.cache: dict[str, bytes | None] = {}

    def read(self, rev: str) -> bytes | None:
        if rev in self.cache:
            return self.cache[rev]
        assert self.proc.stdin and self.proc.stdout
        self.proc.stdin.write(rev.encode() + b"\n")
        self.proc.stdin.flush()
        header = self.proc.stdout.readline().split()
        data = None
        if len(header) == 3 and header[1] == b"blob":
            data = self.proc.stdout.read(int(header[2]))
            self.proc.stdout.read(1)  # trailing newline
        self.cache[rev] = data
        return data

    def close(self) -> None:
        assert self.proc.stdin
        self.proc.stdin.close()
        self.proc.wait()


def shipped_ref() -> str:
    """The ref whose history users actually received: origin/main, else main."""
    for ref in ("refs/remotes/origin/main", "refs/heads/main"):
        if subprocess.run(["git", "-C", str(REPO_ROOT), "rev-parse", "--verify", "--quiet", ref],
                          capture_output=True).returncode == 0:
            return ref
    sys.exit("gen-shipped-hashes: no origin/main or main ref; fetch main first")


def main() -> int:
    entries: set[tuple[str, str]] = set()

    def add(rel: str, data: bytes, crlf_ok: bool) -> None:
        for blob in variants(data, crlf_ok):
            entries.add((rel, hashlib.sha256(blob).hexdigest()))

    reader = BlobReader()
    commits = git("rev-list", shipped_ref(), "--tags", "--", *PATHSPECS).decode().split()
    for commit in commits:
        attrs_blob = reader.read(f"{commit}:.gitattributes")
        rules = parse_gitattributes(attrs_blob.decode("utf-8", "replace") if attrs_blob else "")
        listing = git("ls-tree", "-r", "-z", commit, "--", *PATHSPECS)
        for record in listing.split(b"\0"):
            if not record:
                continue
            meta, repo_path = record.decode().split("\t", 1)
            mode, kind, sha = meta.split()
            # Regular files only: never a symlink (120000) or submodule.
            if kind != "blob" or mode not in ("100644", "100755"):
                continue
            rel = installed_relpath(repo_path)
            if rel is None:
                continue
            data = reader.read(sha)
            if data is not None:
                add(rel, data, checkout_can_be_crlf(file_attrs(rules, repo_path)))
    reader.close()

    # Working tree: tracked and not-yet-added files, normalized back to their
    # LF blob form the way git's clean filter would.
    attrs_path = REPO_ROOT / ".gitattributes"
    rules = parse_gitattributes(attrs_path.read_text(encoding="utf-8") if attrs_path.is_file() else "")
    listing = git("ls-files", "-z", "--cached", "--others", "--exclude-standard", "--", *PATHSPECS)
    for repo_path in sorted(set(listing.decode().split("\0")) - {""}):
        rel = installed_relpath(repo_path)
        file_path = REPO_ROOT / repo_path
        if rel is None or file_path.is_symlink() or not file_path.is_file():
            continue
        attrs = file_attrs(rules, repo_path)
        data = file_path.read_bytes()
        if attrs.get("text") != "unset":
            data = data.replace(b"\r\n", b"\n")
        add(rel, data, checkout_can_be_crlf(attrs))

    lines = [HEADER] + sorted(f"{rel}\t{digest}" for rel, digest in entries)
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    with OUTPUT.open("w", encoding="utf-8", newline="\n") as fh:
        fh.write("\n".join(lines) + "\n")
    print(f"wrote {len(entries)} entries from {len(commits)} commits to {OUTPUT.relative_to(REPO_ROOT).as_posix()}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
